### ISSUE TITLE
Nome do repositório errado no Repl,it

### ISSUE THREAD

**Issue by acreghini** [courselab/prog2020-acreghini#2]
Professor @monacofj , ao abrir a plataforma e apagar uma parte do código que estava editando, a página recarregou e me apresentou os mesmos arquivos, mas com nome do repositório e URL estranhas. Tentei várias vezes e até mudei de navegador, mas aconteceu o mesmo. Estando neste novo repositório, consigo editar normalmente, mas não volta para o meu. Segue print.

![erro_replit](https://user-images.githubusercontent.com/62968909/85640546-75586900-b662-11ea-9f19-00bfb2f91769.PNG)

**Comment by monacofj** [comment]
Wow! Estranho isso.

Eu testei aqui, entrando primeiro no github e de lá clicando no ícone "Work in Repl.it".
Abriu seu repositório normalmente

![image](https://user-images.githubusercontent.com/3980792/85732534-d53a2880-b6d1-11ea-8fcd-00bead942f6d.png)

Pode ser algum problema momentâneo ou algum problema de cache.
Se nada funcionar, você pode: abrir seu Repl.it; no menu superior esqquerdo "My Repls"; ache seu repositório e no menu direito (três pontinhos), delete o repo. Depois volte ao github e tente via o ícone novamente para ver se ele recria. O que está no github nunca é perdido.

Se der certo, por favor abra a issue novamente.
